// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvJD8Ph-gFE53OzN3ubKg47wYhtUJcJZ8',
    appId: '1:766757864946:android:c794acb7032054f5e6576b',
    messagingSenderId: '766757864946',
    projectId: 'signin-a2c1e',
    storageBucket: 'signin-a2c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4rGlmGXFBZH4k6z81HIdxBOrQVluV71c',
    appId: '1:766757864946:ios:f2e83ea8186ef8e1e6576b',
    messagingSenderId: '766757864946',
    projectId: 'signin-a2c1e',
    storageBucket: 'signin-a2c1e.appspot.com',
    androidClientId: '766757864946-fu0s8n0ii21j4ojd2dbhfmhv05irkl8j.apps.googleusercontent.com',
    iosClientId: '766757864946-bj49vueu5hlp54vd6183pbd0d624vgc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleSignin',
  );
}
